apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n0o8whssp-go 
  janus-idp.io/tekton: n0o8whssp-go
  backstage.io/kubernetes-id: n0o8whssp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n0o8whssp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml